BEGIN;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('hero_home', 'home', 'hero', 'video', 'grok', 'Hero editorial Guapacha', 'Video full-bleed in stile yes-dancebiennale: danza sociale, coppie reali, luce calda, Roma Parioli.', 'https://PLACEHOLDER/hero_home.mp4', 'https://PLACEHOLDER/hero_home.jpg', 12, '16:9', 1, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('courses_social', 'home', 'courses', 'video', 'grok', 'Corsi social dance', 'Lezione elegante e autentica, persone reali che imparano e si muovono insieme.', 'https://PLACEHOLDER/courses_social.mp4', 'https://PLACEHOLDER/courses_social.jpg', 10, '16:9', 2, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('wedding_first_dance', 'home', 'wedding', 'video', 'grok', 'Wedding first dance', 'Coreografia romantica e raffinata per il giorno del matrimonio.', 'https://PLACEHOLDER/wedding_first_dance.mp4', 'https://PLACEHOLDER/wedding_first_dance.jpg', 10, '16:9', 3, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('events_night', 'home', 'events', 'video', 'grok', 'Eventi serali', 'Community night, performance e vibrazione upscale.', 'https://PLACEHOLDER/events_night.mp4', 'https://PLACEHOLDER/events_night.jpg', 10, '16:9', 4, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('pro_session', 'home', 'pro', 'video', 'grok', 'Corsi PRO', 'Livello avanzato, correzione tecnica, presenza scenica.', 'https://PLACEHOLDER/pro_session.mp4', 'https://PLACEHOLDER/pro_session.jpg', 10, '16:9', 5, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('private_session', 'home', 'private', 'video', 'grok', 'Sessioni individuali 1:1', 'Percorso personale su postura, musicalità e crescita.', 'https://PLACEHOLDER/private_session.mp4', 'https://PLACEHOLDER/private_session.jpg', 10, '16:9', 6, true) ON CONFLICT (key) DO NOTHING;
INSERT INTO media_assets (key, page, section, asset_type, source, title, description, url, poster_url, duration_seconds, aspect_ratio, sort_order, is_active) VALUES ('community_backstage', 'home', 'community', 'video', 'grok', 'Community backstage', 'Momenti reali, gruppo, energia e identità di studio.', 'https://PLACEHOLDER/community_backstage.mp4', 'https://PLACEHOLDER/community_backstage.jpg', 10, '16:9', 7, true) ON CONFLICT (key) DO NOTHING;
COMMIT;
